# Generated by Django 3.2.5 on 2021-10-27 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('timeToComplete', models.FloatField(null=True)),
                ('numOfErrors', models.IntegerField(null=True)),
                ('errorPerSec', models.FloatField(null=True)),
                ('errorPencentage', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile')),
            ],
        ),
    ]
